import type {
  DeviceCapabilities,
  DeviceConnectivityStatus,
  DeviceProperty,
} from '../../shared/types/canonical.types';
import type { Device } from './device.types';

const NOW = Date.now();
const minutesAgo = (m: number) => new Date(NOW - m * 60_000).toISOString();

function prop(
  id: string,
  key: string,
  label: string,
  value: DeviceProperty['value'],
  unit: string | undefined,
  valueType: DeviceProperty['valueType'],
  writable: boolean,
  updatedMinutesAgo: number,
  min?: number,
  max?: number,
): DeviceProperty {
  return {
    id,
    key,
    label,
    value,
    unit,
    valueType,
    writable,
    updatedAt: minutesAgo(updatedMinutesAgo),
    quality: 'good',
    min,
    max,
  };
}

const NO_CAPS: DeviceCapabilities = {
  telemetry: false,
  commands: false,
  scheduling: false,
  thresholds: false,
};

export const DEVICE_FIXTURES: Device[] = [
  {
    id: 'd1',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d1-temp', 'temperature', 'Temperature', 71.4, '°F', 'number', false, 2),
      prop('d1-hum', 'humidity', 'Humidity', 46, '%', 'number', false, 2),
    ],
  },
  {
    id: 'd2',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d2-temp', 'temperature', 'Temperature', 73.1, '°F', 'number', false, 5),
      prop('d2-hum', 'humidity', 'Humidity', 41, '%', 'number', false, 5),
    ],
  },
  {
    id: 'd3',
    name: 'Main Meter',
    category: 'energy-meter',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d3-power', 'activePower', 'Active Power', 84.2, 'kW', 'number', false, 1),
      prop('d3-energy', 'energy', 'Energy Today', 612, 'kWh', 'number', false, 1),
      prop('d3-voltage', 'voltage', 'Voltage', 230.0, 'V', 'number', false, 1),
      prop('d3-current', 'current', 'Current', 389.4, 'A', 'number', false, 1),
      prop('d3-pf', 'powerFactor', 'Power Factor', 0.94, '', 'number', false, 1),
      prop('d3-freq', 'frequency', 'Frequency', 60.02, 'Hz', 'number', false, 1),
      prop('d3-reactive', 'reactivePower', 'Reactive Power', 30.56, 'kVAR', 'number', false, 1),
      prop('d3-apparent', 'apparentPower', 'Apparent Power', 89.57, 'kVA', 'number', false, 1),
    ],
  },
  {
    id: 'd4',
    name: 'Ground Floor Sub-Meter',
    category: 'energy-meter',
    buildingId: 'b1',
    floorId: 'b1-f2',
    connectivity: 'stale',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(190),
    properties: [
      prop('d4-power', 'activePower', 'Active Power', 22.7, 'kW', 'number', false, 190),
      prop('d4-energy', 'energy', 'Energy Today', 205, 'kWh', 'number', false, 190),
      prop('d4-voltage', 'voltage', 'Voltage', 230.0, 'V', 'number', false, 190),
      prop('d4-current', 'current', 'Current', 103.9, 'A', 'number', false, 190),
      prop('d4-pf', 'powerFactor', 'Power Factor', 0.95, '', 'number', false, 190),
      prop('d4-freq', 'frequency', 'Frequency', 59.98, 'Hz', 'number', false, 190),
      prop('d4-reactive', 'reactivePower', 'Reactive Power', 7.45, 'kVAR', 'number', false, 190),
      prop('d4-apparent', 'apparentPower', 'Apparent Power', 23.89, 'kVA', 'number', false, 190),
    ],
  },
  {
    id: 'd5',
    name: 'CO₂ Sensor',
    category: 'gas',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d5-co2', 'co2', 'CO₂', 612, 'ppm', 'number', false, 3),
      prop('d5-co', 'co', 'CO', 2, 'ppm', 'number', false, 3),
    ],
  },
  {
    id: 'd6',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(4),
    properties: [
      prop('d6-aqi', 'aqi', 'AQI', 38, '', 'number', false, 4),
      prop('d6-iaq', 'iaq', 'IAQ Index', 42, '', 'number', false, 4),
      prop('d6-tvoc', 'tvoc', 'TVOC', 110, 'ppb', 'number', false, 4),
      prop('d6-eco2', 'eco2', 'eCO2', 520, 'ppm', 'number', false, 4),
      prop('d6-pm1', 'pm1', 'PM 1.0', 6, 'µg/m³', 'number', false, 4),
      prop('d6-pm25', 'pm25', 'PM 2.5', 9, 'µg/m³', 'number', false, 4),
      prop('d6-pm10', 'pm10', 'PM 10', 13, 'µg/m³', 'number', false, 4),
    ],
  },
  {
    id: 'd7',
    name: 'Corridor Motion — Floor 2',
    category: 'motion',
    buildingId: 'b1',
    floorId: 'b1-f2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(6),
    properties: [
      prop('d7-count', 'detections', 'Detections (24h)', 47, '', 'number', false, 6),
      prop('d7-batt', 'battery', 'Battery', 91, '%', 'number', false, 6),
      prop('d7-sens', 'sensitivity', 'Sensitivity', 'high', undefined, 'enum', false, 6),
    ],
  },
  {
    id: 'd8',
    name: 'Contact Sensor',
    category: 'contact',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(8),
    properties: [prop('d8-state', 'state', 'Door State', 'closed', undefined, 'enum', false, 8)],
  },
  {
    id: 'd9',
    name: 'Smoke Detector',
    category: 'smoke',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'warning',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(45),
    properties: [
      prop('d9-state', 'state', 'Alarm State', 'normal', undefined, 'enum', false, 45),
      prop('d9-batt', 'battery', 'Battery', 18, '%', 'number', false, 45),
    ],
  },
  {
    id: 'd10',
    name: 'Water Leak Sensor',
    category: 'water-leak',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(10),
    properties: [prop('d10-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 10)],
  },
  {
    id: 'd11',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d11-on', 'on', 'Power', true, undefined, 'boolean', true, 1),
      prop('d11-load', 'load', 'Load', 340, 'W', 'number', false, 1),
      prop('d11-energy', 'energy', 'Energy Today', 4.8, 'kWh', 'number', false, 1),
    ],
  },
  {
    id: 'd12',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'offline',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(720),
    properties: [
      prop('d12-on', 'on', 'Power', false, undefined, 'boolean', true, 720),
      prop('d12-load', 'load', 'Load', 0, 'W', 'number', false, 720),
      prop('d12-energy', 'energy', 'Energy Today', 0, 'kWh', 'number', false, 720),
    ],
  },
  {
    id: 'd13',
    name: 'Building Gateway',
    category: 'gateway-hub',
    buildingId: 'b1',
    floorId: 'b1-f1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d13-count', 'connectedDevices', 'Connected Devices', 12, '', 'number', false, 1),
    ],
  },
  {
    id: 'd14',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d14-temp', 'temperature', 'Temperature', 69.8, '°F', 'number', false, 3),
      prop('d14-hum', 'humidity', 'Humidity', 38, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd15',
    name: 'West Campus Main Meter',
    category: 'energy-meter',
    buildingId: 'b2',
    floorId: 'b2-f1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d15-power', 'activePower', 'Active Power', 51.3, 'kW', 'number', false, 2),
      prop('d15-energy', 'energy', 'Energy Today', 388, 'kWh', 'number', false, 2),
      prop('d15-voltage', 'voltage', 'Voltage', 220.0, 'V', 'number', false, 2),
      prop('d15-current', 'current', 'Current', 253.5, 'A', 'number', false, 2),
      prop('d15-pf', 'powerFactor', 'Power Factor', 0.92, '', 'number', false, 2),
      prop('d15-freq', 'frequency', 'Frequency', 59.95, 'Hz', 'number', false, 2),
      prop('d15-reactive', 'reactivePower', 'Reactive Power', 21.85, 'kVAR', 'number', false, 2),
      prop('d15-apparent', 'apparentPower', 'Apparent Power', 55.76, 'kVA', 'number', false, 2),
    ],
  },
  {
    id: 'd16',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d16-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d16-load', 'load', 'Load', 210, 'W', 'number', false, 2),
    ],
  },
  {
    id: 'd17',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(6),
    properties: [
      prop('d17-aqi', 'aqi', 'AQI', 52, '', 'number', false, 6),
      prop('d17-iaq', 'iaq', 'IAQ Index', 58, '', 'number', false, 6),
      prop('d17-tvoc', 'tvoc', 'TVOC', 220, 'ppb', 'number', false, 6),
      prop('d17-eco2', 'eco2', 'eCO2', 690, 'ppm', 'number', false, 6),
      prop('d17-pm1', 'pm1', 'PM 1.0', 9, 'µg/m³', 'number', false, 6),
      prop('d17-pm25', 'pm25', 'PM 2.5', 14, 'µg/m³', 'number', false, 6),
      prop('d17-pm10', 'pm10', 'PM 10', 21, 'µg/m³', 'number', false, 6),
    ],
  },
  {
    id: 'd18',
    name: 'Riverside Main Meter',
    category: 'energy-meter',
    buildingId: 'b3',
    floorId: 'b3-f1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d18-power', 'activePower', 'Active Power', 63.9, 'kW', 'number', false, 1),
      prop('d18-energy', 'energy', 'Energy Today', 501, 'kWh', 'number', false, 1),
      prop('d18-voltage', 'voltage', 'Voltage', 240.0, 'V', 'number', false, 1),
      prop('d18-current', 'current', 'Current', 277.3, 'A', 'number', false, 1),
      prop('d18-pf', 'powerFactor', 'Power Factor', 0.96, '', 'number', false, 1),
      prop('d18-freq', 'frequency', 'Frequency', 60.05, 'Hz', 'number', false, 1),
      prop('d18-reactive', 'reactivePower', 'Reactive Power', 18.64, 'kVAR', 'number', false, 1),
      prop('d18-apparent', 'apparentPower', 'Apparent Power', 66.56, 'kVA', 'number', false, 1),
    ],
  },
  {
    id: 'd19',
    name: 'Unregistered Sensor #4471',
    category: 'unknown',
    buildingId: 'b3',
    floorId: 'b3-f1',
    spaceId: 'b3-f1-s1',
    connectivity: 'unknown',
    capabilities: NO_CAPS,
    lastSeenAt: minutesAgo(4320),
    properties: [
      prop('d19-raw', 'raw', 'Last Raw Value', '0x1F', undefined, 'string', false, 4320),
    ],
  },

  {
    id: 'd20',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d20-on', 'on', 'Power', true, undefined, 'boolean', true, 3),
      prop('d20-load', 'load', 'Load', 65, 'W', 'number', false, 3),
    ],
  },
  {
    id: 'd21',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d21-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d21-load', 'load', 'Load', 180, 'W', 'number', false, 2),
      prop('d21-energy', 'energy', 'Energy Today', 1.9, 'kWh', 'number', false, 2),
    ],
  },
  {
    id: 'd22',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(7),
    properties: [
      prop('d22-aqi', 'aqi', 'AQI', 44, '', 'number', false, 7),
      prop('d22-iaq', 'iaq', 'IAQ Index', 48, '', 'number', false, 7),
      prop('d22-tvoc', 'tvoc', 'TVOC', 160, 'ppb', 'number', false, 7),
      prop('d22-eco2', 'eco2', 'eCO2', 590, 'ppm', 'number', false, 7),
      prop('d22-pm1', 'pm1', 'PM 1.0', 7, 'µg/m³', 'number', false, 7),
      prop('d22-pm25', 'pm25', 'PM 2.5', 11, 'µg/m³', 'number', false, 7),
      prop('d22-pm10', 'pm10', 'PM 10', 16, 'µg/m³', 'number', false, 7),
    ],
  },
  {
    id: 'd23',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(4),
    properties: [
      prop('d23-on', 'on', 'Power', false, undefined, 'boolean', true, 4),
      prop('d23-load', 'load', 'Load', 0, 'W', 'number', false, 4),
    ],
  },
  {
    id: 'd24',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'offline',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(720),
    properties: [
      prop('d24-on', 'on', 'Power', false, undefined, 'boolean', true, 720),
      prop('d24-load', 'load', 'Load', 0, 'W', 'number', false, 720),
    ],
  },
  {
    id: 'd25',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(9),
    properties: [
      prop('d25-aqi', 'aqi', 'AQI', 41, '', 'number', false, 9),
      prop('d25-iaq', 'iaq', 'IAQ Index', 45, '', 'number', false, 9),
      prop('d25-tvoc', 'tvoc', 'TVOC', 145, 'ppb', 'number', false, 9),
      prop('d25-eco2', 'eco2', 'eCO2', 570, 'ppm', 'number', false, 9),
      prop('d25-pm1', 'pm1', 'PM 1.0', 7, 'µg/m³', 'number', false, 9),
      prop('d25-pm25', 'pm25', 'PM 2.5', 10, 'µg/m³', 'number', false, 9),
      prop('d25-pm10', 'pm10', 'PM 10', 15, 'µg/m³', 'number', false, 9),
    ],
  },
  {
    id: 'd26',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d26-temp', 'temperature', 'Temperature', 72.6, '°F', 'number', false, 3),
      prop('d26-hum', 'humidity', 'Humidity', 43, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd27',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d27-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d27-load', 'load', 'Load', 265, 'W', 'number', false, 2),
      prop('d27-energy', 'energy', 'Energy Today', 3.1, 'kWh', 'number', false, 2),
    ],
  },
  {
    id: 'd28',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d28-on', 'on', 'Power', true, undefined, 'boolean', true, 5),
      prop('d28-load', 'load', 'Load', 58, 'W', 'number', false, 5),
    ],
  },
  {
    id: 'd29',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(4),
    properties: [
      prop('d29-temp', 'temperature', 'Temperature', 70.9, '°F', 'number', false, 4),
      prop('d29-hum', 'humidity', 'Humidity', 40, '%', 'number', false, 4),
    ],
  },
  {
    id: 'd30',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d30-on', 'on', 'Power', true, undefined, 'boolean', true, 1),
      prop('d30-load', 'load', 'Load', 120, 'W', 'number', false, 1),
      prop('d30-energy', 'energy', 'Energy Today', 1.4, 'kWh', 'number', false, 1),
    ],
  },
  {
    id: 'd31',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(6),
    properties: [
      prop('d31-aqi', 'aqi', 'AQI', 35, '', 'number', false, 6),
      prop('d31-iaq', 'iaq', 'IAQ Index', 38, '', 'number', false, 6),
      prop('d31-tvoc', 'tvoc', 'TVOC', 95, 'ppb', 'number', false, 6),
      prop('d31-eco2', 'eco2', 'eCO2', 510, 'ppm', 'number', false, 6),
      prop('d31-pm1', 'pm1', 'PM 1.0', 5, 'µg/m³', 'number', false, 6),
      prop('d31-pm25', 'pm25', 'PM 2.5', 8, 'µg/m³', 'number', false, 6),
      prop('d31-pm10', 'pm10', 'PM 10', 12, 'µg/m³', 'number', false, 6),
    ],
  },
  {
    id: 'd32',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d32-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d32-load', 'load', 'Load', 90, 'W', 'number', false, 2),
      prop('d32-energy', 'energy', 'Energy Today', 0.9, 'kWh', 'number', false, 2),
    ],
  },
  {
    id: 'd33',
    name: 'Motion Sensor',
    category: 'motion',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(11),
    properties: [
      prop('d33-count', 'detections', 'Detections (24h)', 63, '', 'number', false, 11),
      prop('d33-batt', 'battery', 'Battery', 76, '%', 'number', false, 11),
      prop('d33-sens', 'sensitivity', 'Sensitivity', 'medium', undefined, 'enum', false, 11),
    ],
  },
  {
    id: 'd34',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d34-on', 'on', 'Power', false, undefined, 'boolean', true, 3),
      prop('d34-load', 'load', 'Load', 0, 'W', 'number', false, 3),
    ],
  },
  {
    id: 'd35',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'stale',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(240),
    properties: [
      prop('d35-aqi', 'aqi', 'AQI', 58, '', 'number', false, 240),
      prop('d35-iaq', 'iaq', 'IAQ Index', 64, '', 'number', false, 240),
      prop('d35-tvoc', 'tvoc', 'TVOC', 260, 'ppb', 'number', false, 240),
      prop('d35-eco2', 'eco2', 'eCO2', 740, 'ppm', 'number', false, 240),
      prop('d35-pm1', 'pm1', 'PM 1.0', 11, 'µg/m³', 'number', false, 240),
      prop('d35-pm25', 'pm25', 'PM 2.5', 16, 'µg/m³', 'number', false, 240),
      prop('d35-pm10', 'pm10', 'PM 10', 24, 'µg/m³', 'number', false, 240),
    ],
  },
  {
    id: 'd36',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b3',
    floorId: 'b3-f1',
    spaceId: 'b3-f1-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d36-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d36-load', 'load', 'Load', 310, 'W', 'number', false, 2),
    ],
  },
  {
    id: 'd37',
    name: 'Environment Sensor',
    category: 'environment',
    buildingId: 'b3',
    floorId: 'b3-f1',
    spaceId: 'b3-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d37-temp', 'temperature', 'Temperature', 72.0, '°F', 'number', false, 5),
      prop('d37-hum', 'humidity', 'Humidity', 45, '%', 'number', false, 5),
    ],
  },
  {
    id: 'd38',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d38-on', 'on', 'Power', true, undefined, 'boolean', true, 3),
      prop('d38-load', 'load', 'Load', 72, 'W', 'number', false, 3),
    ],
  },
  {
    id: 'd39',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d39-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d39-load', 'load', 'Load', 420, 'W', 'number', false, 2),
    ],
  },
  {
    id: 'd40',
    name: 'Smoke Detector',
    category: 'smoke',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(20),
    properties: [
      prop('d40-state', 'state', 'Alarm State', 'normal', undefined, 'enum', false, 20),
      prop('d40-batt', 'battery', 'Battery', 82, '%', 'number', false, 20),
    ],
  },
  {
    id: 'd41',
    name: 'Motion Sensor',
    category: 'motion',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(15),
    properties: [
      prop('d41-count', 'detections', 'Detections (24h)', 6, '', 'number', false, 15),
      prop('d41-batt', 'battery', 'Battery', 88, '%', 'number', false, 15),
      prop('d41-sens', 'sensitivity', 'Sensitivity', 'low', undefined, 'enum', false, 15),
    ],
  },

  {
    id: 'd42',
    name: 'Fan',
    category: 'fan',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d42-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d42-speed', 'speed', 'Speed', 3, '', 'number', true, 2, 1, 3),
      prop('d42-load', 'load', 'Load', 65, 'W', 'number', false, 2),
      prop('d42-energy', 'energy', 'Energy Today', 0.6, 'kWh', 'number', false, 2),
    ],
  },
  {
    id: 'd43',
    name: 'Lights',
    category: 'light-switch',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d43-on', 'on', 'Power', true, undefined, 'boolean', true, 1),
      prop('d43-load', 'load', 'Load', 280, 'W', 'number', false, 1),
      prop('d43-energy', 'energy', 'Energy Today', 2.1, 'kWh', 'number', false, 1),
    ],
  },
  {
    id: 'd44',
    name: 'AC',
    category: 'thermostat',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: true,
      environment: true,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d44-on', 'on', 'Power', true, undefined, 'boolean', true, 1),
      prop(
        'd44-target',
        'targetTemperature',
        'Set Temperature',
        72,
        '°F',
        'number',
        true,
        1,
        60,
        85,
      ),
      prop('d44-temp', 'temperature', 'Temperature', 75.3, '°F', 'number', false, 1),
      prop('d44-hum', 'humidity', 'Humidity', 44, '%', 'number', false, 1),
      prop('d44-energy', 'energy', 'Energy Today', 3.4, 'kWh', 'number', false, 1),
    ],
  },
  {
    id: 'd45',
    name: 'Door Contact',
    category: 'contact',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(3),
    properties: [prop('d45-state', 'state', 'Door State', 'closed', undefined, 'enum', false, 3)],
  },
  {
    id: 'd46',
    name: 'Motion Sensor',
    category: 'motion',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(4),
    properties: [
      prop('d46-count', 'detections', 'Detections (24h)', 5, '', 'number', false, 4),
      prop('d46-batt', 'battery', 'Battery', 87, '%', 'number', false, 4),
      prop('d46-sens', 'sensitivity', 'Sensitivity', 'medium', undefined, 'enum', false, 4),
    ],
  },
  {
    id: 'd47',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(6),
    properties: [
      prop('d47-aqi', 'aqi', 'AQI', 41, '', 'number', false, 6),
      prop('d47-iaq', 'iaq', 'IAQ Index', 45, '', 'number', false, 6),
      prop('d47-tvoc', 'tvoc', 'TVOC', 150, 'ppb', 'number', false, 6),
      prop('d47-eco2', 'eco2', 'eCO2', 580, 'ppm', 'number', false, 6),
      prop('d47-pm1', 'pm1', 'PM 1.0', 7, 'µg/m³', 'number', false, 6),
      prop('d47-pm25', 'pm25', 'PM 2.5', 11, 'µg/m³', 'number', false, 6),
      prop('d47-pm10', 'pm10', 'PM 10', 16, 'µg/m³', 'number', false, 6),
    ],
  },

  {
    id: 'd48',
    name: 'Energy Meter',
    category: 'energy-meter',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d48-power', 'activePower', 'Active Power', 1.85, 'kW', 'number', false, 1),
      prop('d48-energy', 'energy', 'Energy Today', 8.4, 'kWh', 'number', false, 1),
      prop('d48-voltage', 'voltage', 'Voltage', 120.0, 'V', 'number', false, 1),
      prop('d48-current', 'current', 'Current', 16.6, 'A', 'number', false, 1),
      prop('d48-pf', 'powerFactor', 'Power Factor', 0.93, '', 'number', false, 1),
      prop('d48-freq', 'frequency', 'Frequency', 59.9, 'Hz', 'number', false, 1),
      prop('d48-reactive', 'reactivePower', 'Reactive Power', 0.73, 'kVAR', 'number', false, 1),
      prop('d48-apparent', 'apparentPower', 'Apparent Power', 1.99, 'kVA', 'number', false, 1),
    ],
  },
  {
    id: 'd49',
    name: 'Temp & Humidity Sensor',
    category: 'environment',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      environment: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d49-temp', 'temperature', 'Temperature', 74.8, '°F', 'number', false, 2),
      prop('d49-hum', 'humidity', 'Humidity', 46, '%', 'number', false, 2),
    ],
  },
  {
    id: 'd50',
    name: 'Smoke Sensor',
    category: 'smoke',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d50-state', 'state', 'Alarm State', 'normal', undefined, 'enum', false, 3),
      prop('d50-batt', 'battery', 'Battery', 92, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd51',
    name: 'Gas Leak Sensor',
    category: 'gas',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(4),
    properties: [
      prop('d51-co2', 'co2', 'CO₂', 615, 'ppm', 'number', false, 4),
      prop('d51-co', 'co', 'CO', 1.4, 'ppm', 'number', false, 4),
      prop('d51-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 4),
      prop('d51-batt', 'battery', 'Battery', 88, '%', 'number', false, 4),
    ],
  },
  {
    id: 'd52',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d52-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 1),
      prop('d52-occ', 'occupancyMinutes', 'Occupancy Today', 312, 'min', 'number', false, 1),
      prop('d52-batt', 'battery', 'Battery', 79, '%', 'number', false, 1),
    ],
  },
  {
    id: 'd53',
    name: 'Water Leakage Sensor',
    category: 'water-leak',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d53-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 5),
      prop('d53-batt', 'battery', 'Battery', 81, '%', 'number', false, 5),
    ],
  },
  {
    id: 'd54',
    name: 'Flow Meter',
    category: 'flow-meter',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d54-rate', 'flowRate', 'Flow Rate', 5.2, 'L/min', 'number', false, 2),
      prop('d54-vol', 'totalVolume', 'Total Volume', 940, 'L', 'number', false, 2),
    ],
  },
  {
    id: 'd55',
    name: 'Camera',
    category: 'camera',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(1),
    properties: [prop('d55-power', 'power', 'Power', true, undefined, 'boolean', true, 1)],
  },
  {
    id: 'd56',
    name: 'Door Lock',
    category: 'lock',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d56-locked', 'locked', 'Locked', true, undefined, 'boolean', true, 1),
      prop('d56-method', 'lastMethod', 'Last Access Method', 'keypad', undefined, 'enum', false, 1),
      prop('d56-batt', 'battery', 'Battery', 74, '%', 'number', false, 1),
    ],
  },
  {
    id: 'd57',
    name: 'TV Socket',
    category: 'socket',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d57-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d57-load', 'load', 'Load', 95, 'W', 'number', false, 2),
      prop('d57-energy', 'energy', 'Energy Today', 0.4, 'kWh', 'number', false, 2),
      prop('d57-voltage', 'voltage', 'Voltage', 120.4, 'V', 'number', false, 2),
    ],
  },
  {
    id: 'd58',
    name: 'Desk Lamp',
    category: 'lamp',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: true, thresholds: false },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d58-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d58-brightness', 'brightness', 'Brightness', 70, '%', 'number', true, 2, 0, 100),
      prop('d58-load', 'load', 'Load', 12, 'W', 'number', false, 2),
    ],
  },

  {
    id: 'd59',
    name: 'Camera',
    category: 'camera',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(1),
    properties: [prop('d59-power', 'power', 'Power', true, undefined, 'boolean', true, 1)],
  },
  {
    id: 'd60',
    name: 'Door Lock',
    category: 'lock',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d60-locked', 'locked', 'Locked', false, undefined, 'boolean', true, 3),
      prop('d60-method', 'lastMethod', 'Last Access Method', 'keypad', undefined, 'enum', false, 3),
      prop('d60-batt', 'battery', 'Battery', 68, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd61',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d61-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 2),
      prop('d61-occ', 'occupancyMinutes', 'Occupancy Today', 186, 'min', 'number', false, 2),
      prop('d61-batt', 'battery', 'Battery', 90, '%', 'number', false, 2),
    ],
  },

  {
    id: 'd62',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d62-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 1),
      prop('d62-occ', 'occupancyMinutes', 'Occupancy Today', 275, 'min', 'number', false, 1),
      prop('d62-batt', 'battery', 'Battery', 84, '%', 'number', false, 1),
    ],
  },
  {
    id: 'd63',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d63-aqi', 'aqi', 'AQI', 39, '', 'number', false, 5),
      prop('d63-iaq', 'iaq', 'IAQ Index', 43, '', 'number', false, 5),
      prop('d63-tvoc', 'tvoc', 'TVOC', 120, 'ppb', 'number', false, 5),
      prop('d63-eco2', 'eco2', 'eCO2', 540, 'ppm', 'number', false, 5),
      prop('d63-pm1', 'pm1', 'PM 1.0', 6, 'µg/m³', 'number', false, 5),
      prop('d63-pm25', 'pm25', 'PM 2.5', 10, 'µg/m³', 'number', false, 5),
      prop('d63-pm10', 'pm10', 'PM 10', 14, 'µg/m³', 'number', false, 5),
    ],
  },
  {
    id: 'd64',
    name: 'Workstation Socket',
    category: 'socket',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d64-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d64-load', 'load', 'Load', 68, 'W', 'number', false, 2),
      prop('d64-energy', 'energy', 'Energy Today', 0.5, 'kWh', 'number', false, 2),
      prop('d64-voltage', 'voltage', 'Voltage', 119.8, 'V', 'number', false, 2),
    ],
  },

  {
    id: 'd65',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d65-presence', 'presence', 'Presence', 'vacant', undefined, 'enum', false, 3),
      prop('d65-occ', 'occupancyMinutes', 'Occupancy Today', 95, 'min', 'number', false, 3),
      prop('d65-batt', 'battery', 'Battery', 77, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd66',
    name: 'TV Socket',
    category: 'socket',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d66-on', 'on', 'Power', false, undefined, 'boolean', true, 2),
      prop('d66-load', 'load', 'Load', 0, 'W', 'number', false, 2),
      prop('d66-energy', 'energy', 'Energy Today', 0.8, 'kWh', 'number', false, 2),
      prop('d66-voltage', 'voltage', 'Voltage', 121.1, 'V', 'number', false, 2),
    ],
  },
  {
    id: 'd67',
    name: 'Camera',
    category: 'camera',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(4),
    properties: [prop('d67-power', 'power', 'Power', true, undefined, 'boolean', true, 4)],
  },

  {
    id: 'd68',
    name: 'Water Leakage Sensor',
    category: 'water-leak',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(6),
    properties: [
      prop('d68-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 6),
      prop('d68-batt', 'battery', 'Battery', 85, '%', 'number', false, 6),
    ],
  },
  {
    id: 'd69',
    name: 'Flow Meter',
    category: 'flow-meter',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d69-rate', 'flowRate', 'Flow Rate', 7.8, 'L/min', 'number', false, 3),
      prop('d69-vol', 'totalVolume', 'Total Volume', 1240, 'L', 'number', false, 3),
    ],
  },
  {
    id: 'd70',
    name: 'Door Lock',
    category: 'lock',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d70-locked', 'locked', 'Locked', true, undefined, 'boolean', true, 1),
      prop(
        'd70-method',
        'lastMethod',
        'Last Access Method',
        'fingerprint',
        undefined,
        'enum',
        false,
        1,
      ),
      prop('d70-batt', 'battery', 'Battery', 95, '%', 'number', false, 1),
    ],
  },

  {
    id: 'd71',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d71-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 2),
      prop('d71-occ', 'occupancyMinutes', 'Occupancy Today', 248, 'min', 'number', false, 2),
      prop('d71-batt', 'battery', 'Battery', 82, '%', 'number', false, 2),
    ],
  },
  {
    id: 'd72',
    name: 'AQI Sensor',
    category: 'air-quality',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: false, scheduling: false, thresholds: true },
    lastSeenAt: minutesAgo(7),
    properties: [
      prop('d72-aqi', 'aqi', 'AQI', 43, '', 'number', false, 7),
      prop('d72-iaq', 'iaq', 'IAQ Index', 47, '', 'number', false, 7),
      prop('d72-tvoc', 'tvoc', 'TVOC', 135, 'ppb', 'number', false, 7),
      prop('d72-eco2', 'eco2', 'eCO2', 560, 'ppm', 'number', false, 7),
      prop('d72-pm1', 'pm1', 'PM 1.0', 7, 'µg/m³', 'number', false, 7),
      prop('d72-pm25', 'pm25', 'PM 2.5', 11, 'µg/m³', 'number', false, 7),
      prop('d72-pm10', 'pm10', 'PM 10', 15, 'µg/m³', 'number', false, 7),
    ],
  },
  {
    id: 'd73',
    name: 'Workstation Socket',
    category: 'socket',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d73-on', 'on', 'Power', true, undefined, 'boolean', true, 3),
      prop('d73-load', 'load', 'Load', 72, 'W', 'number', false, 3),
      prop('d73-energy', 'energy', 'Energy Today', 0.6, 'kWh', 'number', false, 3),
      prop('d73-voltage', 'voltage', 'Voltage', 120.7, 'V', 'number', false, 3),
    ],
  },

  {
    id: 'd74',
    name: 'Camera',
    category: 'camera',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: { telemetry: true, commands: true, scheduling: false, thresholds: false },
    lastSeenAt: minutesAgo(1),
    properties: [prop('d74-power', 'power', 'Power', true, undefined, 'boolean', true, 1)],
  },
  {
    id: 'd75',
    name: 'Door Lock',
    category: 'lock',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d75-locked', 'locked', 'Locked', false, undefined, 'boolean', true, 2),
      prop('d75-method', 'lastMethod', 'Last Access Method', 'keypad', undefined, 'enum', false, 2),
      prop('d75-batt', 'battery', 'Battery', 71, '%', 'number', false, 2),
    ],
  },
  {
    id: 'd76',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d76-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 1),
      prop('d76-occ', 'occupancyMinutes', 'Occupancy Today', 401, 'min', 'number', false, 1),
      prop('d76-batt', 'battery', 'Battery', 88, '%', 'number', false, 1),
    ],
  },

  {
    id: 'd77',
    name: 'Gas Leak Sensor',
    category: 'gas',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d77-co2', 'co2', 'CO₂', 640, 'ppm', 'number', false, 3),
      prop('d77-co', 'co', 'CO', 1.8, 'ppm', 'number', false, 3),
      prop('d77-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 3),
      prop('d77-batt', 'battery', 'Battery', 91, '%', 'number', false, 3),
    ],
  },
  {
    id: 'd78',
    name: 'Water Leakage Sensor',
    category: 'water-leak',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(5),
    properties: [
      prop('d78-state', 'state', 'Leak State', 'normal', undefined, 'enum', false, 5),
      prop('d78-batt', 'battery', 'Battery', 86, '%', 'number', false, 5),
    ],
  },
  {
    id: 'd79',
    name: 'Door Lock',
    category: 'lock',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: false,
      battery: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d79-locked', 'locked', 'Locked', true, undefined, 'boolean', true, 2),
      prop(
        'd79-method',
        'lastMethod',
        'Last Access Method',
        'fingerprint',
        undefined,
        'enum',
        false,
        2,
      ),
      prop('d79-batt', 'battery', 'Battery', 77, '%', 'number', false, 2),
    ],
  },

  {
    id: 'd80',
    name: 'Energy Meter',
    category: 'energy-meter',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d80-power', 'activePower', 'Active Power', 1.35, 'kW', 'number', false, 1),
      prop('d80-energy', 'energy', 'Energy Today', 6.7, 'kWh', 'number', false, 1),
      prop('d80-voltage', 'voltage', 'Voltage', 120.0, 'V', 'number', false, 1),
      prop('d80-current', 'current', 'Current', 12.4, 'A', 'number', false, 1),
      prop('d80-pf', 'powerFactor', 'Power Factor', 0.91, '', 'number', false, 1),
      prop('d80-freq', 'frequency', 'Frequency', 60.1, 'Hz', 'number', false, 1),
      prop('d80-reactive', 'reactivePower', 'Reactive Power', 0.62, 'kVAR', 'number', false, 1),
      prop('d80-apparent', 'apparentPower', 'Apparent Power', 1.48, 'kVA', 'number', false, 1),
    ],
  },
  {
    id: 'd81',
    name: 'Human Presence Sensor',
    category: 'presence',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: false,
      scheduling: false,
      thresholds: false,
      occupancy: true,
      battery: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d81-presence', 'presence', 'Presence', 'occupied', undefined, 'enum', false, 2),
      prop('d81-occ', 'occupancyMinutes', 'Occupancy Today', 260, 'min', 'number', false, 2),
      prop('d81-batt', 'battery', 'Battery', 80, '%', 'number', false, 2),
    ],
  },
  {
    id: 'd82',
    name: 'Workstation Socket',
    category: 'socket',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d82-on', 'on', 'Power', true, undefined, 'boolean', true, 3),
      prop('d82-load', 'load', 'Load', 60, 'W', 'number', false, 3),
      prop('d82-energy', 'energy', 'Energy Today', 0.5, 'kWh', 'number', false, 3),
      prop('d82-voltage', 'voltage', 'Voltage', 119.5, 'V', 'number', false, 3),
    ],
  },

  {
    id: 'd83',
    name: 'Light Switch',
    category: 'light-switch',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(2),
    properties: [
      prop('d83-on', 'on', 'Power', true, undefined, 'boolean', true, 2),
      prop('d83-load', 'load', 'Load', 210, 'W', 'number', false, 2),
      prop('d83-energy', 'energy', 'Energy Today', 1.6, 'kWh', 'number', false, 2),
    ],
  },
  {
    id: 'd84',
    name: 'AC',
    category: 'thermostat',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: false,
      thresholds: true,
      environment: true,
      energy: true,
    },
    lastSeenAt: minutesAgo(1),
    properties: [
      prop('d84-on', 'on', 'Power', true, undefined, 'boolean', true, 1),
      prop(
        'd84-target',
        'targetTemperature',
        'Set Temperature',
        70,
        '°F',
        'number',
        true,
        1,
        60,
        85,
      ),
      prop('d84-temp', 'temperature', 'Temperature', 71.2, '°F', 'number', false, 1),
      prop('d84-hum', 'humidity', 'Humidity', 40, '%', 'number', false, 1),
      prop('d84-energy', 'energy', 'Energy Today', 4.1, 'kWh', 'number', false, 1),
    ],
  },
  {
    id: 'd85',
    name: 'Equipment Socket',
    category: 'socket',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    connectivity: 'online',
    capabilities: {
      telemetry: true,
      commands: true,
      scheduling: true,
      thresholds: false,
      energy: true,
    },
    lastSeenAt: minutesAgo(3),
    properties: [
      prop('d85-on', 'on', 'Power', true, undefined, 'boolean', true, 3),
      prop('d85-load', 'load', 'Load', 340, 'W', 'number', false, 3),
      prop('d85-energy', 'energy', 'Energy Today', 2.8, 'kWh', 'number', false, 3),
      prop('d85-voltage', 'voltage', 'Voltage', 122.0, 'V', 'number', false, 3),
    ],
  },
] satisfies Device[];

export function connectivityBreakdown(devices: Device[]): Record<DeviceConnectivityStatus, number> {
  const breakdown: Record<DeviceConnectivityStatus, number> = {
    online: 0,
    offline: 0,
    stale: 0,
    warning: 0,
    error: 0,
    disabled: 0,
    unknown: 0,
  };
  for (const device of devices) {
    breakdown[device.connectivity]++;
  }
  return breakdown;
}
