import type { Automation, AutomationExecution } from './automation.types';

const NOW = Date.now();
const daysAgo = (d: number) => new Date(NOW - d * 24 * 60 * 60_000).toISOString();

export const AUTOMATION_FIXTURES: Automation[] = [
  {
    id: 'a1',
    name: 'High Lobby Temperature Alert',
    description: 'Notify and open a maintenance request when the lobby sensor reads above 78°F.',
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd1',
      propertyId: 'd1-temp',
      operator: '>',
      value: '78',
    },
    conditions: [],
    actions: [
      { type: 'notification', message: 'Lobby temperature exceeded 78°F.' },
      {
        type: 'maintenance',
        maintenanceTitle: 'Investigate lobby HVAC',
        maintenancePriority: 'medium',
      },
    ],
    buildingId: 'b1',
    floorId: 'b1-f1',
    schedule: null,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(2),
  },
  {
    id: 'a2',
    name: 'Evening Office Lights Off',
    description: 'Turn off the Open Office lighting switch at 7pm on weekdays.',
    status: 'enabled',
    trigger: { type: 'time', timeOfDay: '19:00' },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd11', propertyId: 'd11-on', value: 'false' }],
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    schedule: { days: [1, 2, 3, 4, 5], startHour: 0, endHour: 24 },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(15),
  },
  {
    id: 'a3',
    name: 'Low Battery Alert — Smoke Detector',
    description:
      'Notify facilities when the mechanical room smoke detector battery drops below 20%.',
    status: 'disabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd9',
      propertyId: 'd9-batt',
      operator: '<',
      value: '20',
    },
    conditions: [],
    actions: [
      { type: 'notification', message: 'Mechanical Room Smoke Detector battery critically low.' },
    ],
    buildingId: 'b1',
    floorId: 'b1-f3',
    schedule: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(30),
  },
  {
    id: 'a4',
    name: 'Water Leak Emergency Response',
    description: 'Raise an urgent maintenance request the instant a leak sensor trips.',
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd10',
      propertyId: 'd10-state',
      operator: '==',
      value: 'leak',
    },
    conditions: [],
    actions: [
      { type: 'notification', message: 'Water leak detected — mechanical room.' },
      {
        type: 'maintenance',
        maintenanceTitle: 'Water leak — mechanical room',
        maintenancePriority: 'urgent',
      },
    ],
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s2',
    schedule: null,
    createdAt: daysAgo(75),
    updatedAt: daysAgo(75),
  },
  {
    id: 'a5',
    name: 'Manager Room — Entry Lighting',
    description: 'Turns the lights on when the door opens.',
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd45',
      propertyId: 'd45-state',
      operator: '==',
      value: 'open',
    },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd43', propertyId: 'd43-on', value: 'true' }],
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    schedule: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'a6',
    name: 'Lab 1 Gas Leak Emergency Response',
    description:
      "Raises an urgent maintenance request and alerts facilities the instant the lab's gas sensor detects a leak.",
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd77',
      propertyId: 'd77-state',
      operator: '==',
      value: 'leak',
    },
    conditions: [],
    actions: [
      { type: 'notification', message: 'Gas leak detected — Lab 1.' },
      { type: 'maintenance', maintenanceTitle: 'Gas leak — Lab 1', maintenancePriority: 'urgent' },
    ],
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    schedule: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },
  {
    id: 'a7',
    name: 'Lab 1 — Lights On When Unlocked',
    description:
      "Turns the lab's lights on whenever the door lock is opened, so no one walks into a dark lab.",
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd79',
      propertyId: 'd79-locked',
      operator: '==',
      value: 'false',
    },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd83', propertyId: 'd83-on', value: 'true' }],
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    schedule: null,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(5),
  },
  {
    id: 'a8',
    name: 'Reception — After-Hours Auto Lock',
    description: 'Automatically locks the front door every night at 10pm.',
    status: 'enabled',
    trigger: { type: 'time', timeOfDay: '22:00' },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd75', propertyId: 'd75-locked', value: 'true' }],
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    schedule: null,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(10),
  },
  {
    id: 'a9',
    name: 'Open Office — Workstation Power Saver',
    description: 'Turns off the shared workstation socket once the hot-desking area goes vacant.',
    status: 'enabled',
    trigger: { type: 'occupancy-changed', occupancyStatus: 'vacant' },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd64', propertyId: 'd64-on', value: 'false' }],
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    schedule: null,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
  {
    id: 'a10',
    name: 'Mechanical Room — High Water Flow Alert',
    description: 'Notifies facilities if water flow spikes, a common early sign of a burst pipe.',
    status: 'disabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd69',
      propertyId: 'd69-rate',
      operator: '>',
      value: '15',
    },
    conditions: [],
    actions: [
      { type: 'notification', message: 'Unusually high water flow detected — Mechanical Room.' },
    ],
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    schedule: null,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(35),
  },
  {
    id: 'a11',
    name: 'Meeting Room — TV Off When Vacant',
    description:
      "Powers down the conference TV once the room's presence sensor reports vacant, saving standby energy between meetings.",
    status: 'enabled',
    trigger: {
      type: 'device-property',
      deviceId: 'd65',
      propertyId: 'd65-presence',
      operator: '==',
      value: 'vacant',
    },
    conditions: [],
    actions: [{ type: 'device-command', deviceId: 'd66', propertyId: 'd66-on', value: 'false' }],
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    schedule: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
];

export const AUTOMATION_EXECUTION_FIXTURES: AutomationExecution[] = [
  {
    id: 'ax1',
    automationId: 'a1',
    triggeredAt: daysAgo(2),
    triggerSource: 'Lobby Temp/Humidity — temperature > 78°F',
    finalState: 'completed',
    actionResults: [
      { action: 'Send notification: Lobby temperature exceeded 78°F.', success: true },
      { action: 'Create maintenance: Investigate lobby HVAC', success: true },
    ],
  },
  {
    id: 'ax2',
    automationId: 'a2',
    triggeredAt: daysAgo(1),
    triggerSource: 'Scheduled time 19:00',
    finalState: 'completed',
    actionResults: [{ action: 'Set Open Office Lighting Switch Power to Off', success: true }],
  },
  {
    id: 'ax3',
    automationId: 'a2',
    triggeredAt: daysAgo(2),
    triggerSource: 'Scheduled time 19:00',
    finalState: 'failed',
    actionResults: [
      {
        action: 'Set Open Office Lighting Switch Power to Off',
        success: false,
        detail: 'Device offline',
      },
    ],
  },
  {
    id: 'ax4',
    automationId: 'a4',
    triggeredAt: daysAgo(5),
    triggerSource: 'Mechanical Room Water Sensor — state == leak',
    finalState: 'partially-failed',
    actionResults: [
      { action: 'Send notification: Water leak detected — mechanical room.', success: true },
      {
        action: 'Create maintenance: Water leak — mechanical room',
        success: false,
        detail: 'Maintenance service timeout',
      },
    ],
  },
  {
    id: 'ax5',
    automationId: 'a7',
    triggeredAt: daysAgo(1),
    triggerSource: 'Lab 1 Door Lock — locked == false',
    finalState: 'completed',
    actionResults: [{ action: 'Set Lab 1 Light Switch Power to On', success: true }],
  },
  {
    id: 'ax6',
    automationId: 'a9',
    triggeredAt: daysAgo(3),
    triggerSource: 'Open Office — occupancy became vacant',
    finalState: 'completed',
    actionResults: [{ action: 'Set Open Office Workstation Socket Power to Off', success: true }],
  },
  {
    id: 'ax7',
    automationId: 'a11',
    triggeredAt: daysAgo(1),
    triggerSource: 'Meeting Room Human Presence Sensor — presence == vacant',
    finalState: 'completed',
    actionResults: [{ action: 'Set Meeting Room TV Socket Power to Off', success: true }],
  },
];
