import type { AccessAssignment } from './access-assignment.types';

const NOW = Date.now();
const hoursAgo = (h: number) => new Date(NOW - h * 60 * 60_000).toISOString();
const hoursFromNow = (h: number) => new Date(NOW + h * 60 * 60_000).toISOString();

export const ACCESS_ASSIGNMENT_FIXTURES: AccessAssignment[] = [
  {
    id: 'aa1',
    principalName: 'Ray Solano',
    principalType: 'vendor-technician',
    roleLabel: 'Vendor Technician — HVAC repair',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    validFrom: hoursAgo(20),
    validUntil: hoursFromNow(4),
    createdAt: hoursAgo(20),
    maintenanceId: 'm1',
    vendorId: 'v1',
  },
  {
    id: 'aa2',
    principalName: 'Priya Anand',
    principalType: 'staff',
    roleLabel: 'Facilities inspection — quarterly walkthrough',
    buildingId: 'b2',
    validFrom: hoursAgo(200),
    validUntil: hoursAgo(196),
    createdAt: hoursAgo(200),
  },
  {
    id: 'aa3',
    principalName: 'Tomas Reyes',
    principalType: 'vendor-technician',
    roleLabel: 'Vendor Technician — plumbing estimate',
    buildingId: 'b3',
    floorId: 'b3-f2',
    validFrom: hoursAgo(48),
    validUntil: hoursFromNow(24),
    createdAt: hoursAgo(48),
    revokedAt: hoursAgo(30),
    vendorId: 'v3',
  },
  {
    id: 'aa4',
    principalName: 'Alicia Ward',
    principalType: 'vendor-technician',
    roleLabel: 'Vendor Technician — annual fire inspection',
    buildingId: 'b1',
    floorId: 'b1-f3',
    validFrom: hoursFromNow(48),
    validUntil: hoursFromNow(56),
    createdAt: hoursAgo(2),
    vendorId: 'v4',
  },
  {
    id: 'aa5',
    principalName: 'Jordan Meyers',
    principalType: 'staff',
    roleLabel: 'Desk owner — standing access',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    validFrom: hoursAgo(2000),
    validUntil: hoursFromNow(2000),
    createdAt: hoursAgo(2000),
  },
  {
    id: 'aa6',
    principalName: 'Dana Whitfield',
    principalType: 'staff',
    roleLabel: 'Room owner — standing access',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    validFrom: hoursAgo(720),
    validUntil: hoursFromNow(720),
    createdAt: hoursAgo(720),
  },
  {
    id: 'aa7',
    principalName: 'Marcus Webb',
    principalType: 'staff',
    roleLabel: 'Store manager — standing access',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    validFrom: hoursAgo(1500),
    validUntil: hoursFromNow(1500),
    createdAt: hoursAgo(1500),
  },
  {
    id: 'aa8',
    principalName: 'Sam Okafor',
    principalType: 'staff',
    roleLabel: 'Facilities coordinator — standing access',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    validFrom: hoursAgo(900),
    validUntil: hoursFromNow(900),
    createdAt: hoursAgo(900),
  },
  {
    id: 'aa9',
    principalName: 'Elena Cruz',
    principalType: 'staff',
    roleLabel: 'Desk owner — standing access',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s2',
    validFrom: hoursAgo(600),
    validUntil: hoursFromNow(600),
    createdAt: hoursAgo(600),
  },
  {
    id: 'aa10',
    principalName: 'Morgan Lee',
    principalType: 'staff',
    roleLabel: 'Front desk — standing access',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    validFrom: hoursAgo(1100),
    validUntil: hoursFromNow(1100),
    createdAt: hoursAgo(1100),
  },
  {
    id: 'aa11',
    principalName: 'Devon Park',
    principalType: 'staff',
    roleLabel: 'Lab technician — standing access',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    validFrom: hoursAgo(800),
    validUntil: hoursFromNow(800),
    createdAt: hoursAgo(800),
  },
  {
    id: 'aa12',
    principalName: 'Jamie Ortiz',
    principalType: 'staff',
    roleLabel: 'Desk owner — standing access',
    buildingId: 'b2',
    floorId: 'b2-f2',
    spaceId: 'b2-f2-s1',
    validFrom: hoursAgo(500),
    validUntil: hoursFromNow(500),
    createdAt: hoursAgo(500),
  },
];
