import type { MaintenanceRequest } from './maintenance.types';

const NOW = Date.now();
const daysAgo = (d: number) => new Date(NOW - d * 24 * 60 * 60_000).toISOString();

export const MAINTENANCE_FIXTURES: MaintenanceRequest[] = [
  {
    id: 'm1',
    title: 'AC unit making loud noise',
    description: 'Recurring rattling noise from the rooftop AC unit during business hours.',
    buildingId: 'b1',
    floorId: 'b1-f3',
    spaceId: 'b1-f3-s1',
    priority: 'high',
    status: 'in-progress',
    category: 'hvac',
    requester: 'Dana Whitfield',
    assignee: 'Marcus Reed',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    timeline: [
      { id: 'm1-t1', at: daysAgo(3), label: 'Request created', actor: 'Dana Whitfield' },
      { id: 'm1-t2', at: daysAgo(2), label: 'Triaged as HVAC / High priority' },
      { id: 'm1-t3', at: daysAgo(1), label: 'Assigned to Marcus Reed' },
    ],
  },
  {
    id: 'm2',
    title: 'Flickering lights in Meeting Room',
    description: 'Lights flicker intermittently, possibly ballast issue.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    priority: 'medium',
    status: 'assigned',
    category: 'electrical',
    requester: 'Priya Anand',
    assignee: 'Marcus Reed',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    timeline: [
      { id: 'm2-t1', at: daysAgo(2), label: 'Request created', actor: 'Priya Anand' },
      { id: 'm2-t2', at: daysAgo(1), label: 'Assigned to Marcus Reed' },
    ],
  },
  {
    id: 'm3',
    title: 'Water leak near mechanical room',
    description: 'Water leak sensor flagged near the west mechanical room drain.',
    buildingId: 'b3',
    floorId: 'b3-f2',
    spaceId: 'b3-f2-s2',
    deviceId: 'd10',
    priority: 'urgent',
    status: 'triage',
    category: 'plumbing',
    requester: 'System (device alert)',
    createdAt: daysAgo(0.2),
    updatedAt: daysAgo(0.2),
    timeline: [{ id: 'm3-t1', at: daysAgo(0.2), label: 'Auto-created from device alert' }],
  },
  {
    id: 'm4',
    title: 'Smart switch unresponsive',
    description: 'Meeting Room switch not responding to commands.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    deviceId: 'd12',
    priority: 'medium',
    status: 'created',
    category: 'electrical',
    requester: 'Priya Anand',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    timeline: [{ id: 'm4-t1', at: daysAgo(1), label: 'Request created', actor: 'Priya Anand' }],
  },
  {
    id: 'm5',
    title: 'Replace ceiling tile — Lobby',
    description: 'Water-stained ceiling tile near the main lobby entrance.',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s1',
    priority: 'low',
    status: 'complete',
    category: 'general',
    requester: 'Dana Whitfield',
    assignee: 'Ken Ito',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
    timeline: [
      { id: 'm5-t1', at: daysAgo(10), label: 'Request created', actor: 'Dana Whitfield' },
      { id: 'm5-t2', at: daysAgo(8), label: 'Assigned to Ken Ito' },
      { id: 'm5-t3', at: daysAgo(6), label: 'Marked complete', actor: 'Ken Ito' },
    ],
  },
  {
    id: 'm6',
    title: 'Fire extinguisher inspection overdue',
    description: 'Annual inspection tag expired on 3rd floor extinguisher.',
    buildingId: 'b1',
    floorId: 'b1-f3',
    priority: 'high',
    status: 'verify',
    category: 'safety',
    requester: 'Facilities Team',
    assignee: 'Ken Ito',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(2),
    timeline: [
      { id: 'm6-t1', at: daysAgo(14), label: 'Request created' },
      { id: 'm6-t2', at: daysAgo(9), label: 'Assigned to Ken Ito' },
      { id: 'm6-t3', at: daysAgo(2), label: 'Inspection completed, pending verification' },
    ],
  },
  {
    id: 'm7',
    title: 'Wi-Fi dead zone — Lab 1',
    description: 'Weak signal reported near the back of Lab 1.',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    priority: 'medium',
    status: 'closed',
    category: 'it',
    requester: 'Sam Okafor',
    assignee: 'IT Team',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(25),
    timeline: [
      { id: 'm7-t1', at: daysAgo(30), label: 'Request created', actor: 'Sam Okafor' },
      { id: 'm7-t2', at: daysAgo(27), label: 'Access point relocated' },
      { id: 'm7-t3', at: daysAgo(25), label: 'Closed — resolved', actor: 'IT Team' },
    ],
  },
  {
    id: 'm8',
    title: 'Duplicate: HVAC noise',
    description: 'Duplicate of an existing HVAC noise complaint.',
    buildingId: 'b1',
    floorId: 'b1-f3',
    priority: 'low',
    status: 'rejected',
    category: 'hvac',
    requester: 'Anonymous',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    timeline: [
      { id: 'm8-t1', at: daysAgo(3), label: 'Request created' },
      { id: 'm8-t2', at: daysAgo(3), label: 'Rejected — duplicate of m1' },
    ],
  },
  {
    id: 'm9',
    title: 'Desk outlet not working',
    description: 'One of the power outlets under the standing desks has stopped working.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    priority: 'low',
    status: 'assigned',
    category: 'electrical',
    requester: 'Jordan Meyers',
    assignee: 'Marcus Reed',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    timeline: [
      { id: 'm9-t1', at: daysAgo(2), label: 'Request created', actor: 'Jordan Meyers' },
      { id: 'm9-t2', at: daysAgo(1), label: 'Assigned to Marcus Reed' },
    ],
  },
  {
    id: 'm10',
    title: 'AC unit not cooling adequately',
    description:
      'Manager Room AC set to 72 °F but room temperature stays above 75 °F. Possible refrigerant issue.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    deviceId: 'd44',
    priority: 'high',
    status: 'in-progress',
    category: 'hvac',
    requester: 'Dana Whitfield',
    assignee: 'Marcus Reed',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0.5),
    timeline: [
      { id: 'm10-t1', at: daysAgo(2), label: 'Request created', actor: 'Dana Whitfield' },
      { id: 'm10-t2', at: daysAgo(1), label: 'Triaged as HVAC / High priority' },
      {
        id: 'm10-t3',
        at: daysAgo(0.5),
        label: 'Assigned to Marcus Reed — refrigerant check scheduled',
      },
    ],
  },
  {
    id: 'm11',
    title: 'Fan making grinding noise at speed 4+',
    description:
      'Ceiling fan in Manager Room produces a grinding sound when set above speed 3. Bearing replacement needed.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    deviceId: 'd42',
    priority: 'medium',
    status: 'assigned',
    category: 'general',
    requester: 'Priya Anand',
    assignee: 'Ken Ito',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    timeline: [
      { id: 'm11-t1', at: daysAgo(4), label: 'Request created', actor: 'Priya Anand' },
      { id: 'm11-t2', at: daysAgo(1), label: 'Assigned to Ken Ito' },
    ],
  },
  {
    id: 'm12',
    title: 'Door contact sensor intermittently offline',
    description:
      'Manager Room door contact sensor drops connectivity every few hours. Battery or firmware issue suspected.',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    deviceId: 'd45',
    priority: 'low',
    status: 'triage',
    category: 'it',
    requester: 'System (device alert)',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    timeline: [{ id: 'm12-t1', at: daysAgo(1), label: 'Auto-created from device alert' }],
  },
];
