import type { Booking } from './booking.types';

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function daysFromNowAt(days: number, hour: number, minute: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

const NOW_ISO = new Date().toISOString();

export const BOOKING_FIXTURES: Booking[] = [
  {
    id: 'bk1',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    guestName: 'Miguel Torres',
    numberOfGuests: 1,
    checkInDate: daysFromNow(-2),
    checkOutDate: daysFromNow(3),
    status: 'checked-in',
    notes: 'Extended stay — corporate booking.',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNowAt(-2, 10, 15),
  },
  {
    id: 'bk2',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s3',
    guestName: 'Elena Petrova',
    numberOfGuests: 1,
    checkInDate: daysFromNow(-10),
    checkOutDate: daysFromNow(-7),
    status: 'checked-out',
    needsCleaning: true,
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-14),
    updatedAt: daysFromNowAt(-7, 11, 30),
  },
  {
    id: 'bk3',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    guestName: 'Daniel Osei',
    numberOfGuests: 2,
    checkInDate: daysFromNow(2),
    checkOutDate: daysFromNow(5),
    status: 'reserved',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNowAt(-1, 9, 0),
  },
  {
    id: 'bk4',
    buildingId: 'b1',
    floorId: 'b1-f1',
    spaceId: 'b1-f1-s2',
    guestName: 'Whitfield Group',
    numberOfGuests: 4,
    checkInDate: daysFromNow(-3),
    checkOutDate: daysFromNow(-1),
    status: 'reserved',
    notes: 'Never arrived — needs a no-show/cancel decision.',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-9),
    updatedAt: daysFromNowAt(-9, 14, 45),
  },
  {
    id: 'bk5',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s2',
    guestName: 'Priya Shah',
    numberOfGuests: 6,
    checkInDate: daysFromNow(0),
    checkOutDate: daysFromNow(1),
    status: 'checked-in',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-2),
    updatedAt: NOW_ISO,
  },
  {
    id: 'bk6',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    guestName: 'Test Conference Block',
    numberOfGuests: 10,
    checkInDate: daysFromNow(6),
    checkOutDate: daysFromNow(8),
    status: 'cancelled',
    notes: 'Client cancelled the event.',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-4),
    updatedAt: daysFromNowAt(-1, 16, 0),
  },
  {
    id: 'bk7',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s1',
    guestName: 'Amara Nwosu',
    numberOfGuests: 1,
    checkInDate: daysFromNow(-20),
    checkOutDate: daysFromNow(-18),
    status: 'checked-out',
    needsCleaning: true,
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-24),
    updatedAt: daysFromNowAt(-18, 10, 0),
  },
  {
    id: 'bk8',
    buildingId: 'b2',
    floorId: 'b2-f1',
    spaceId: 'b2-f1-s2',
    guestName: 'Sam Okafor',
    numberOfGuests: 3,
    checkInDate: daysFromNow(10),
    checkOutDate: daysFromNow(14),
    status: 'reserved',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(0),
    updatedAt: daysFromNowAt(0, 8, 30),
  },
  {
    id: 'bk9',
    buildingId: 'b1',
    floorId: 'b1-f2',
    spaceId: 'b1-f2-s1',
    guestName: 'Yuki Tanaka',
    numberOfGuests: 2,
    checkInDate: daysFromNow(0),
    checkOutDate: daysFromNow(2),
    status: 'reserved',
    createdBy: 'Front Desk',
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNowAt(-1, 13, 20),
  },
];
